/* eslint-disable no-unused-vars */
export enum TEST_ENV_GLOBAL {
  ENV = 'TEST_ENV',
  SLUG = 'TEST_SLUG',
  DISPATCHER_URL = 'TEST_DISPATCHER_URL',
  DISPATCHER_CRED_EMAIL = 'TEST_DISPATCHER_CRED_EMAIL',
  DISPATCHER_CRED_PASSWORD = 'TEST_DISPATCHER_CRED_PASSWORD',
  DISPATCHER_COMPANY_ID = 'TEST_DISPATCHER_COMPANY_ID',
  DISPATCHER_COMPANY_NAME = 'TEST_DISPATCHER_COMPANY_NAME',
  SENDER_BOOKING_URL = 'TEST_SENDER_BOOKING_URL',
  SENDER_IND_CRED_EMAIL = 'TEST_SENDER_IND_EMAIL',
  SENDER_IND_CRED_PASSWORD = 'TEST_SENDER_IND_CRED_PASSWORD',
  SENDER_CORP_CRED_EMAIL = 'TEST_SENDER_CORP_EMAIL',
  SENDER_CORP_CRED_PASSWORD = 'TEST_SENDER_CORP_PASSWORD',
  PARTNER_VALID_CIP = 'TEST_PARTNER_VALID_CIP',
  PARTNER_EXISTING_CIP = 'TEST_PARTNER_EXISTING_CIP',
}
